
services:
  llfactura:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: shinsenter/laravel:latest
    container_name: container-llfactura
    volumes:
      - .:/var/www/html
    networks:
      - redPrincipal
     
networks:
  redPrincipal:
    external: true

