<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Inventario>
 */
class InventarioFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // return [
        //     'codigo' => faker()->regexify('[A-Z]{5}[0-4]{3}'),
        //     'detalle' => faker()->word(),
        //     'precio1' => faker()->randomFloat(2),
        //     'precio2' => faker()->randomFloat(2),
        //     'precio3' => faker()->randomFloat(2),
        //     'rubro' => faker()->word(),
        // ];

        return [
            'codigo' => fake()->unique()->ean13,
            'detalle' => fake()->randomElement([
                "Arroz",
                "Azúcar",
                "Leche",
                "Pan",
                "Huevos",
                "Mantequilla",
                "Queso",
                "Yogur",
                "Jugo de Naranja",
                "Café",
                "Té",
                "Galletas",
                "Cereal",
                "Pasta",
                "Salsa de Tomate",
                "Aceite de Oliva",
                "Aceite Vegetal",
                "Harina",
                "Sal",
                "Pimienta",
                "Avena",
                "Mermelada",
                "Miel",
                "Atún enlatado",
                "Sardinas enlatadas",
                "Sopa enlatada",
                "Frijoles enlatados",
                "Vegetales enlatados",
                "Puré de papas instantáneo",
                "Snacks de papas",
                "Chocolate",
                "Chicles",
                "Caramelos",
                "Refrescos",
                "Agua embotellada",
                "Jugo de frutas",
                "Cerveza",
                "Vino",
                "Champán",
                "Whisky",
                "Vodka",
                "Ron",
                "Gin",
                "Licor",
                "Detergente para ropa",
                "Suavizante para ropa",
                "Jabón en barra",
                "Jabón líquido",
                "Shampoo",
                "Acondicionador",
                "Pasta de dientes",
                "Cepillos de dientes",
                "Enjuague bucal",
                "Desodorante",
                "Papel higiénico",
                "Toallas de papel",
                "Servilletas",
                "Bolsas de basura",
                "Aluminio",
                "Film plástico",
                "Esponjas",
                "Limpiador multiusos",
                "Desinfectante",
                "Insecticida",
                "Velas",
                "Fósforos",
                "Encendedores",
                "Pilas",
                "Bombillas",
                "Linternas",
                "Toallas sanitarias",
                "Tampones",
                "Pañales",
                "Toallitas húmedas",
                "Alimento para perros",
                "Alimento para gatos",
                "Arena para gatos",
                "Semillas para pájaros",
                "Juguetes para mascotas",
                "Platos para mascotas",
                "Camas para mascotas",
                "Ropa para mascotas",
                "Collares para mascotas",
                "Correas para mascotas",
                "Productos para entrenamiento de mascotas",
                "Medicamentos para mascotas",
                "Vitaminas para mascotas",
                "Cremas para el cuerpo",
                "Lociones para el cuerpo",
                "Protector solar",
                "Repelente de insectos",
                "Almohadas",
                "Sábanas",
                "Cobijas",
                "Toallas de baño",
                "Batas de baño",
                "Pantuflas",
                "Tijeras",
                "Cortauñas",
                "Pinzas",
                "Cepillos para el cabello",
                "Peines"
            ]),
            'costo' => fake()->randomFloat(2, 1, 1000),
            'precio1' => fake()->randomFloat(2, 10, 100),
            'precio2' => fake()->randomFloat(2, 20, 200),
            'precio3' => fake()->randomFloat(2, 30, 300),
            'iva' => fake()->randomElement([21, 10.5]),
            'rubro' => fake()->randomElement(['General', 'Electrónica', 'Alimentación']),
            'proveedor' => fake()->randomElement(['General', 'Diarco', 'Vital','MAUSE']),
            'marca' => fake()->randomElement(['Nike', 'Ford', 'Dell','MAUSE']),

            'pesable' => fake()->randomElement(['si', 'no']),
            'controlStock' => fake()->randomElement(['si', 'no']),
            'empresa_id' => 1,
        ];
    }
}
